```{r echo = FALSE, warning = FALSE}
source("init.R")
```

# Why does it look like this? {#sec-app-look-like}

*Last modified on `r format(fs::file_info("appendix-a.qmd")$modification_time, '%d. %B %Y at %H:%M:%S')`*

> *"A quote." --- Dan Meyer*

## Used R packages

This is a printout of the `init.R` file, which can be found on GitHub

```{r}
#| eval: false
pacman::p_load(tidyverse, ggforce, viridis, knitr, patchwork)
```

## Used theme of the visualitations

```{r}
#| eval: false
theme_book <- function() {
  theme_minimal() +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(size = 16, face = "bold"),
          plot.subtitle = element_text(size = 12, face = "italic"),
          plot.caption = element_text(face = "italic"),
          axis.title = element_text(size = 12, face = "bold"),
          axis.text = element_text(size = 11),
          legend.title = element_text(face = "bold"))
}
```




## Used color palettes

```{r}
#| eval: false
col_pal <- \(n, alpha) plasma(n = n, alpha = alpha)
c6_pal <- col_pal(6, 1)
```


## References {.unnumbered}