
```{r}
p1_square <- ggplot() +
  theme_void() +
  coord_equal() +
  scale_x_continuous(breaks = seq(-5, 5, 1), limits = c(-1.25, 1.25)) +
  scale_y_continuous(breaks = seq(-5, 5, 1), limits = c(-1.25, 1)) +
  geom_tile(aes(x = 0, y = 0, width = 2, height = 2),
            fill = "#FCA63680", color = "#FCA636FF", alpha = 0.2, linewidth = 0.75) +
  annotate("text", x = 0, y = 0.25, label = expression(A~"="~(3*"m"*-5*"m")*"²"), 
           size = 7.5, color = "black") +
  annotate("text", x = -0.375, y = -0.25, label = expression(phantom(A)~"="~bold("4m²")), 
           size = 7.5, color = "black") +
  annotate("text", x = c(-1, 1), y = -1.15, label = c("3m", "5m"), color = "#FCA636FF", 
           size = 6, fontface = 2) +
  labs(title = "This is the square") +
  theme(plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 12, face = "italic"))

p2_square_root <- ggplot() +
  theme_void() +
  coord_equal() +
  scale_x_continuous(breaks = seq(-5, 5, 1), limits = c(-1.25, 1.25)) +
  scale_y_continuous(breaks = seq(-5, 5, 1), limits = c(-1.25, 1)) +
  geom_tile(aes(x = 0, y = 0, width = 2, height = 2), linetype = 2,
            fill = "#FCA63680", color = "#FCA63680", alpha = 0.1, linewidth = 0.75) +
  annotate("segment", x = 1, y = -1, xend = 1, yend = 1, linewidth = 1.75, color = "#FCA636FF") +
  annotate("text", x = 0, y = 0, label = "A = 4m²", fontface = 2, 
           size = 7.5, color = "gray50") +
  annotate("text", x = 1.2, y = 0, label = expression(sqrt(4*"m"^2)~"="~bold("2m")), size = 6, 
           color = "#FCA636FF", angle = -90) +
  labs(title = "This is the root") +
  theme(plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 12, face = "italic"))


p1_square_many <- ggplot() +
  theme_void() +
  ## theme_minimal() +
  coord_equal() +
  scale_x_continuous(breaks = seq(-5, 5, 1), limits = c(-1, 1)) +
  scale_y_continuous(breaks = seq(-5, 5, 1), limits = c(-1, 1)) +
  geom_tile(aes(x = c(-0.5, -0.5, 0.5, 0.5), y = c(-0.5, 0.5, -0.5, 0.5), 
                width = c(0.5, 1, 0.75, 0.35), 
                height = c(0.5, 1, 0.75, 0.35)), linetype = 1,
            fill = "#FCA63680", color = "#FCA636FF", alpha = 0.2, linewidth = 0.75) +
  annotate("text", x = c(-0.5, -0.5, 0.5, 0.5), y = c(-0.5, 0.5, -0.5, 0.5), 
           label = round(c(0.5, 1, 0.75, 0.35)^2, 1)*10, size = 7.5, color = "black",
           fontface = 2) +
  labs(title = "This are many squares") +
  theme(plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 12, face = "italic"))

p2_square_sum <- ggplot() +
  theme_void() +
  ##theme_minimal() +
  coord_equal() +
  scale_x_continuous(breaks = seq(-5, 5, 1), limits = c(-1, 1)) +
  scale_y_continuous(breaks = seq(-5, 5, 1), limits = c(-1, 1)) +
  geom_tile(aes(x = 0, y = 0, width = 1.39, height = 1.39),
            fill = "#FCA63680", color = "#FCA636FF", alpha = 0.2, linewidth = 0.75) +
  annotate("text", x = 0, y = 0, size = 7.5, color = "black", label = expression(sum()*bold("19")),
           fontface = 2) +
  annotate("text", x = 0, y = -0.81, label = expression(sqrt(19)~"="~bold("4.35")), 
           size = 5, color = "#FCA636FF", fontface = 2) +
  annotate("text", x = 0.8, y = 0, label = expression(sqrt(19)~"="~bold("4.35")),
           size = 5, color = "#FCA636FF", fontface = 2, angle = -90) +
  labs(title = "This is the sum of squares") +
  theme(plot.title = element_text(size = 16, face = "bold"),
        plot.subtitle = element_text(size = 12, face = "italic"))
```

| Name | Symbol | Description |
|:------------------|:----------------:|:------------------|
| **outcome**, response, endpoint, dependent variable | $y$ | *The right-hand side (abbr. RHS) of the model. Describing the values measured in an experiment or study.* |
| **influencer**, influential variable, risk factor, fixed effect, independent variable | $x$ | *The left-hand side (abbr. LHS) of the model. Describing the influential variables in an experiment or study.* |
| **random effect** | $z$ | *A factor that provides a description of an grouping variable, which is not part of the controlled experimental setting.* |
| **explanator**, explanatory variable | $x$ | **Explanation** --- *The influencer is used to describe or explain the change of the outcome.* |
| **predictor**, predictive variable | $x$ | **Prediction** --- *The influencer is used to predict values of the outcome.* |
| **focal explanator**, **focal predictor**, focal variable | $x$ | **Main effect** --- *In a model with multiple influencers, the focal variable is the variable of primary interest.* |
| **covariate**, covariable | $c$ | **Continuous $\boldsymbol{x}$** --- *The influencer is a numeric variable with continuous values.* |
| **factor A**, factorial variable, categorical variable | $f_A$ | **Categorical $\boldsymbol{x}$** ---  *The influencer is discrete, functioning as a grouping variable, such as an experimental group or a treatment.* |
| **levels**, groups, treatment groups | $A.1$ to $A.j$ | *The discrete groups included in one factor $\boldsymbol{f_A}$.* |

: Table of terms used in the statistical modelling. The terms in bold are used here. Depending on the scientific background, the usage of these terms can vary widely. {#tbl-names-regression}
