```{r echo = FALSE}
source("init.R")
```

# What is a model? {#sec-what-is-a-model}

*Last modified on `r format(fs::file_info("chapter-03-what-is-a-model.qmd")$modification_time, '%d. %B %Y at %H:%M:%S')`*

> *"A quote." --- Dan Meyer*

## General background


| Application | Symbol | Name | Description |
|:-------------|:--------:|:------------------|:------------------|
|  | $y$ | **outcome**, response, endpoint, dependent variable | *The right-hand side (abbr. RHS) of the model. Describing the values measured in an experiment or study.* |
|  | $x$ | **influencer**, influential variable, risk factor, fixed effect, independent variable | *The left-hand side (abbr. LHS) of the model. Describing the influential  variables in an experiment or study.* |
|  | $z$ | **random effect** | *A factor that provides a description of an grouping variable, which is not part of the controlled experimental setting.* |
| Explanation | $x$ | **explanator**, explanatory variable | *The influencer is used to describe or explain the outcome.* |
| Prediction | $x$ | **predictor**, predictive variable | *The influencer is used to predict the outcome.* |
| Main effect | $x$ | **focal explanator**, **focal predictor**, focal variable | *In a model with multiple influencers, the focal variable is the variable of primary interest.* |
| Continuous $x$ | $c$ | **covariate**, covariable | *The influencer is a numeric variable with continuous values.* |
| Categorical $x$ | $f_A$ | **factor A**, factorial variable, categorical variable | *The influencer is discrete, functioning as a grouping variable, such as an experimental group or a treatment.*  |
| Factor $f_A$ | $A.1$ to $A.j$ | **levels**, groups, treatment groups | *The discrete groups included in one factor A.*  |

: Table of terms used in the statistical modelling. The terms in bold are used here. Depending on the scientific background, the usage of these terms can vary widely.  {#tbl-names-regression tbl-colwidths="$$20, 5, 30, 45$$"}

A sentence why we use $y$ and not $x$ for mean and other stuff.


@mccullagh2002statistical [What is a statistical model?](https://projecteuclid.org/journals/annals-of-statistics/volume-30/issue-5/What-is-a-statistical-model/10.1214/aos/1035844977.pdf)

@appleton1995we [What do we mean by a statistical model?](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.4780140209?casa_token=jLDogF46zS8AAAAA%3AKOKHMTgbj4gK8ayVXmT1GaXq7slv9i3VGqzA184yydwKUjsDIszepgOaeMQc_L5hRY-TpLZvgDDIdDea)

@hand2019purpose [What Is the Purpose of Statistical Modeling?](https://hdsr.mitpress.mit.edu/pub/9qsbf3hz/release/2?from=603&to=744)

@spanos2006statistical [Where do statistical models come from? Revisiting the problem of specification](https://arxiv.org/pdf/math.ST/0610849)

@gilchrist1984statistical [Statistical modelling](https://nzdr.ru/data/media/biblio/kolxoz/M/MV/MVsa/Gilchrist%20W.%20Statistical%20modelling%20with%20quantile%20functions%20(Chapman,%202000)(ISBN%201584881747)(317s)_MVsa_.pdf)

## Theoretical background

## R packages used

## Data

## Alternatives 

Further tutorials and R packages on XXX

## Glossary

term

: what does it mean.

## The meaning of "Data Science" in this chapter.

- itemize with max. 5-6 words

## Summary

## References {.unnumbered}