```{r echo = FALSE}
pacman::p_load(tidyverse)
```

# Tales of data 

*Last modified on `r format(fs::file_info("chapter-10-preface.qmd")$modification_time, '%d. %B %Y at %H:%M:%S')`*

> *"X-Factor, the unfathomable. We live in a world where dreams and reality are closely intertwined, where facts often seem like figments of the imagination that we cannot explain. Can you distinguish between truth and lies? Yours, Jonathan Frakes." --- German intro of Beyond Belief: Fact or Fiction*


Once upon a time Cadiergues and his team won the Nobel Prize in Stockholm for their work with dog and cat fleas @cadiergues2000comparison. This sparked a time of increased scientific research on fleas of all types of hosts, with scientists studying them in great detail. A wealth of research questions remained to be addressed, while funding opportunities lay in wait. We now have the great opportunity to use open-source data to revisit all the exciting findings in flea research. What are our main research topics and questions that we want to cover?


Unfortunately, none of this ever happened in our branch of reality. But it might happen in countless other branches @everett1957relative.

## References {.unnumbered}