```{r echo = FALSE, warning = FALSE, message = FALSE}
source("init.R")
```

# What is science? {#sec-what-is-science}

*Last modified on `r format(fs::file_info("chapter-01-what-is-science.qmd")$modification_time, '%d. %B %Y at %H:%M:%S')`*

> *"Reality is negotiable." --- Tim Ferriss*

The first chapter of this book is already the hardest. I started writing this chapter very early on, perhaps even before any of the others. Yet it took the longest to finish. The question is simple: What is science? The more I researched, the more complicated the answer became. Or the other way around. I followed the advice of Wolfgang Pauli. Pauli defined the scientific method as "taking up a subject repeatedly. Thinking about it. Setting it aside. Gathering new empirical material. And continuing this process for years if necessary. In this way, the conscious mind stimulates the unconscious mind. If anything, this is the only way to achieve results." Therefore, I tried to read and find answers to the question of what science might be. Perhaps science is, at its core, something personal. However, science also has objective aspects that I want to present here. Ultimately, decide for yourself what science truly is.

### What is not science?

Mathematics and psychoanalysis have no experiments

### What is the opposite of science?

Cargo cult science

conspiracy theories @douglas2023conspiracy and @grimes2016viability

### How to do science?

"As a scientist, you are a professional writer," Joshua Schimel said. @schimel2012writing

Pauli defined the scientific method as "taking up a subject repeatedly. Thinking about it. Setting it aside. Gathering new empirical material. And continuing this process for years if necessary. In this way, the conscious mind stimulates the unconscious mind. If anything, this is the only way to achieve results." @fischer2022stunde. This is more or less about taking a chair and sitting in the middle of the room and getting bored as long as possible. Doing so sparks creativity.

> *"Many scientific topics can only be solved once all aspects have been explicitly formulated. The mind is not sufficiently prepared for this, as it can only ever focus on small sections at a time. Systematic thinking is only possible when writing, i.e. recording the results of one's thinking and relating them to other aspects." --- Otto Kruse @kruse2007keine*

## General background

> *"Any sufficiently advanced technology is indistinguishable from magic." --- Arthur C. Clarke's Third Law @clarke1968clarke*

Full quote

> *"Reality is negotiable. Outside of science and law, all rules can be bent or broken, and it doesn’t require being unethical." --- Tim Ferriss*

Idea of hypotheses

Science is guessing and falsification

@chalmers2013thing [What is this thing called Science?](https://www.pmf.unizg.hr/_download/repository/1._Dodatna_literatura_%28filozofija_znanosti%29%5B3%5D.pdf)

@feynman1966science [What is science](https://www-oc.chemie.uni-regensburg.de/diaz/media/docs/feynman_what-is-science_68.pdf)

@campbell1952science [What is science?](https://www.whatisscience.info/files/what_is_science_rd1.pdf)

@clark2025models [Models Demystified: A Practical Guide from Linear Regression to Deep Learning](https://m-clark.github.io/book-of-models/)

@cox2017statistical [Statistical Thinking for the 21st Century](https://statsthinking21.github.io/statsthinking21-core-site/index.html)

@deutsch2011beginning [The beginning of infinity: Explanations that transform the world](https://www.academia.edu/download/106176299/rtx120400544p.pdf)

[David Deutsch > Quotes](https://www.goodreads.com/author/quotes/103190.David_Deutsch)

## Theoretical background

## R packages used

## Data

## Alternatives 

Further tutorials and R packages on XXX

## Glossary

term

: what does it mean.

## The meaning of "Models of Reality" in this chapter.

- itemize with max. 5-6 words

## Summary

## References {.unnumbered}