# Prelude {.unnumbered .unlisted} 

Light. 

She couldn't see anything. Her eyes had to adjust to the brightness. She was alone in the light. 

The light traveled in a straight line through floating particles in the air. Squares of light slowly turn and dance. They are trying to find the optimal position and size. 

The stage is set. She takes a step. Then another. She feels the creak of the moist wooden stage. She turned her head toward the seats. 

Her voice was crystal clear in the cold air. "I don't think this will work, Jeff! The whole stage is rotten. There's no structure behind it." 

Darkness again. The light bleeds out. She felt alone in the dark. From below, Jeff asked in disbelief, "What are you doing? Fixing the stage? Can we continue then? I'll try to help you, but I don't understand why." 

Emma was an actress, not a craftsman. "I have been doing this for a long time. I need to understand the stage and how everything works. It's important for us."

A long pause of silence. "The reality of the play," Jeff grumbled and sank into his seat. They won't be able to start for a long time.

--------------------------------------------------------------------------------


This will be a long journey... it's a hell of a time.

I need to see it. Therefore, this book is a visualization whenever it is possible or feasible. Some more complex models will be described rather than visualized.

There are better mathematical or theoretical books. I would recommend the book by Westfall and Arias (2020)@westfall2020understanding. It is an enjoyable read and provides a wealth of information on regression models. The visuals are mediocre at best. The R code is outdated and not state of the art for the 21st century.

Some ideas are not new. I will present them in a different way. I think this is an effective approach to writing a book. The book aims to teach you and enable you to teach statistics to beginners. It may also be beneficial for more advanced classes, but my emphasis was always on the uninformed learners.

Lying to children or some angels will be hurt. Sometimes math is a shield to hide behind. Not really the math itself but the mathematical notations. If you cant speak the math language you cannot follow the train of thought. Because communication the the search for compliance, misunderstanding a language can be barrier. 

Machine room of science

Bloody beginners and the curse of knowledge

> *"To write a book you must become the book." — Naval Ravikant*


> *"Life is difficult." --- M. Scott Peck's, The Road Less Traveled *


> *"Ludwig Boltzman, who spent much of his life studying statistical mechanics, died in 1906, by his own hand. Paul Ehrenfest, carrying on the work, died similarly in 1933. Now it is our turn to study statistical mechanics. Perhaps it will be wise to approach the subject cautiously." --- Opening lines of 'States of Matter', by D.L. Goodstein.*

## References {.unlisted .unnumbered} 
